services:
  esphome:
    # image: esphome/esphome:2024.2.1
    image: esphome/esphome:2024.3.0-dev20240301
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./:/config:rw
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
    # devices:
    #   - /dev/ttyUSB1:/dev/ttyUSB0
    network_mode: host
    # esphome won't resolve mDNS names for mqtt logs?
    # https://github.com/esphome/esphome/issues/96
    extra_hosts:
      - home.local:192.168.2.159
