# Basic Config
substitutions:
  devicename: generic-relay-3

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

network:
    enable_ipv6: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 0 # (UART logging interferes with cse7766)
  level: INFO

ota:

mqtt:
  broker: home.home.arpa
  discovery_unique_id_generator: mac
  use_abbreviations: false


# Device Specific Config
uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S31 Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

sensor:
  - platform: wifi_signal
    name: "Sonoff S31 WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Sonoff S31 Current"
      accuracy_decimals: 1
      filters:
        - throttle_average: 60s
    voltage:
      name: "Sonoff S31 Voltage"
      accuracy_decimals: 1
      filters:
        - throttle: 60s
    power:
      name: "Sonoff S31 Power"
      accuracy_decimals: 1
      filters:
        - throttle: 60s

switch:
  - platform: gpio
    name: "Sonoff S31 Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: True